name: Create Pull Request for Upstream Sync
on:
  push:
    branches:
      - upstream-sync
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: upstream-sync
      - name: Install Forgejo CLI
        run: |
          curl -sSL https://codeberg.org/forgejo-contrib/forgejo-cli/releases/download/latest/forgejo-cli-x86_64-linux.tar.gz | tar -xz -C /usr/local/bin
      - name: Create Pull Request
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          fj --host "${FORGEJO_SERVER_URL}" auth add-key "${FORGEJO_TOKEN}"
          fj pr create --title "Sync with upstream" --body "This pull request syncs the latest changes from the upstream repository." --repo "${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}" --base main --head upstream-sync
