name: Create Pull Request for Upstream Sync
on:
  push:
    branches:
      - upstream-sync
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: upstream-sync
      - name: Install Forgejo CLI
        run: |
          curl -sSL https://codeberg.org/forgejo-contrib/forgejo-cli/releases/download/latest/forgejo-cli-x86_64-linux.tar.gz | tar -xz -C /usr/local/bin
      - name: Create Pull Request
        run: |
          fj --host "${FORGEJO_SERVER_URL}" auth add-key "${FORGEJO_ACTOR}" "${{ secrets.FORGEJO_TOKEN }}"
          fj auth list
