name: Create Pull Request for Upstream Sync
on:
  push:
    branches:
      - upstream-sync
  workflow_dispatch:

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: upstream-sync
      - uses: https://github.com/actions-rust-lang/setup-rust-toolchain@v2
      - uses: https://github.com/cargo-bins/cargo-binstall@main
      - name: Install Forgejo CLI
        run: cargo binstall forgejo-cli

      - name: Create Pull Request
        run: |
          fj --host "${FORGEJO_SERVER_URL}" auth add-key "${FORGEJO_ACTOR}" "${FORGEJO_TOKEN}"
          fj auth list