# SPDX-FileCopyrightText: 2026 Mssol94 <magnus@bitbunker.page>
#
# SPDX-License-Identifier: MPL-2.0
name: "Upstream Sync"
on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-git@v1
      - name: Sync upstream and create PR
        run: |
          # Add upstream
          git remote add upstream https://github.com/serokell/deploy-rs.git
          git fetch upstream

          upstream_branch="master"
          head="ci-upstream-sync"
          base="master"

          upstream_commit=$(git rev-parse upstream/${upstream_branch})

          if git rev-parse HEAD | grep -q "$upstream_commit"; then
            echo "No new commits from upstream. Exiting."
            exit 0
          fi

          git checkout -b ci-upstream-sync upstream/${upstream_branch}
          git push origin ci-upstream-sync --force

          existing_pr=$(
            curl --silent --fail-with-body "$FORGEJO_SERVER_URL/api/v1/repos/$FORGEJO_REPOSITORY/pulls?state=open&labels=1" \
              -H "Content-Type: application/json" | jq -r '.[0].id // empty'
          )

          if [ -n "$existing_pr" ]; then
            echo "An open PR for upstream sync already exists (PR ID: $existing_pr). Exiting."
            exit 0
          fi

          pr_title="Sync latest commits from upstream"
          pr_body="This PR syncs the latest commits from the upstream repository."

          jq -n \
            --arg base "$base" \
            --arg head "$head" \
            --arg title "$pr_title" \
            --arg body "$pr_body" \
            '{
              "base": $base,
              "head": $head,
              "title": $title,
              "body": $body,
              "labels": [1]
            }' |
            curl --fail-with-body "$FORGEJO_SERVER_URL/api/v1/repos/$FORGEJO_REPOSITORY/pulls" \
              -H "Authorization: token $FORGEJO_TOKEN" \
              -H "Content-Type: application/json" \
              -d @-
